# Generated by Django 3.0.7 on 2020-08-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserParks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('park_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nest_box_helper.Park')),
            ],
            options={
                'verbose_name_plural': 'User Parks',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('species', models.CharField(blank=True, max_length=50)),
                ('eggs', models.PositiveIntegerField(default='0')),
                ('live_young', models.PositiveIntegerField(default='0')),
                ('dead_young', models.PositiveIntegerField(default='0')),
                ('nest_status', models.CharField(choices=[('NO', 'No Nest'), ('IN', 'Incomplete Nest'), ('AN', 'New nest built on top of old'), ('CN', 'Complete Nest'), ('DN', 'Damaged Nest'), ('FN', 'Flattened Nest'), ('NN', 'Non-avian Nest'), ('RN', 'Nest Gone')], default='NO', max_length=2)),
                ('adult_activity', models.CharField(choices=[('NO', 'No Adult Activity'), ('AA', 'At or on nest, then flushed'), ('BA', 'Building nest/carrying material'), ('DA', 'Dead Adults at Nest'), ('FA', 'Feeding young at the nest'), ('RA', 'Stayed on nest while box checked'), ('VA', 'Parents in vicinity during check')], default='NO', max_length=2)),
                ('young_status', models.CharField(blank=True, choices=[('NO', 'No young - Presumed dead'), ('FY', 'Fully Feathered Young'), ('HY', 'Hatchling Young'), ('NY', 'Naked Young'), ('PY', 'Partially Feathered'), ('VY', 'Vocal Young - You could not see them'), ('YY', 'Young presumed to have fledged')], max_length=2)),
                ('management_activity', models.CharField(choices=[('NO', 'No management done'), ('AM', 'Removed house sparrow nest/eggs'), ('EM', 'Unhatched host eggs removed'), ('NM', 'Cleaned nest box for next inhabitant'), ('PM', 'Removed pests from box')], default='NO', max_length=2)),
                ('cowbird_evidence', models.CharField(default='None', max_length=4)),
                ('comments', models.TextField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('attempt_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nest_box_helper.Attempt')),
                ('monitor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveIntegerField(default=1)),
                ('box_description', models.CharField(default='None', max_length=100)),
                ('monitor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('park_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nest_box_helper.Park')),
            ],
            options={
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='box_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nest_box_helper.Box'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='monitor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
